title: GATE CS39
subtitle: "A guide for GATE CS"
description: "GATE CS39 is a complete one-stop solution for gate preparation."
share: "GATE CS39 , A guide for gate cse preparation"
url: https://gatecs39.github.io/
markdown: kramdown
permalink: pretty
exclude: ['node_modules']
